### ISSUE TITLE
how I can make this container run in the background when my local SSH connection is disconnected

### ISSUE THREAD

**Issue by 3038843920** [dockur/windows#103]
Hello, excuse me, I would like to ask you how I can make this container run in the background when my local SSH connection is disconnected

**Comment by duanqiao12138** [comment]
change -it to -itd

**Comment by 3038843920** [comment]
> change -it to -itd

I didn't know much about this command before, thank you very much for telling me about it

**Comment by 3038843920** [comment]
> The example command contains `-rm` which means it removes the container if you exit the command. So to keep it running, just run the same command without `-rm`.
> 
> But this question is more about how Docker works, it has nothing to do with this container.

Understanding. I have added the - d parameter as mentioned by the senior below, and the problem has been resolved. Nevertheless, I am very grateful for taking the time to respond to my request for help

**Comment by xiaoweiChen** [comment]
@3038843920 
I want to know how to connect the windows container with SSH, and use command line to do some operation in Windows system.
Could you share the way for me?
