### ISSUE TITLE
Import qcow2 file in a Windows container's storage

### ISSUE THREAD

**Issue by GuiguiDaan** [dockur/windows#185]
Hi everyone, I just have a question.

That's possible to import  a .qcow2 file in the Windows Containers with a docker-compose for use him as a main storage ?

Regards

**Comment by GuiguiDaan** [comment]
Amazing, everything is working ! Thank you for your help !

Be careful to rename the qcow2 file you want to import to "data.qcow2", else the container will create a new storage file 😉

**Comment by ggdd2008** [comment]
![image](https://github.com/dockur/windows/assets/87541945/84b4c5b9-0860-4237-b0a4-6abf210ba1af)
"It's been stuck on this screen and won't move,What is the cause of this issue?

**Comment by ggdd2008** [comment]
I attempted to install Windows 2008 on my computer, but it keeps getting stuck on "Setup is starting" without moving on to where I can select the partition.
