### ISSUE TITLE
Container IP?

### ISSUE THREAD

**Issue by davidlfox** [dockur/windows#191]
Maybe I'm just misconfiguring Docker, but is it possible to run this from a Windows host and connect on 3389? `docker inspect mycontainer` shows 172.17.0.3, but RDP won't connect to that. `ipconfig` on the Windows Docker container shows 20.20.20.21, but RDP won't connect to that.

Is there some other IP configuration that needs to happen to connect? Connecting to 3389 on localhost doesn't work since RDP is already listening on the host box.

**Comment by davidlfox** [comment]
got it--had to change the docker config and then manually change the RDP port in the registry

**Comment by kdurant** [comment]
@davidlfox Could you give me  detailed steps? I encount this problem too.

**Comment by davidlfox** [comment]
in docker compose:
```
ports:
      - 8006:8006
      - 3390:3390/tcp
      - 3390:3390/udp
```

in windows (after its installed) you need to change the port RDP listens on to be `3390` (or your chosen port from docker compose). this is a registry change (google for the full path) and then a reboot probably required

**Comment by kdurant** [comment]
@davidlfox  What is IP address of RDP?

**Comment by davidlfox** [comment]
localhost, or wherever youre running the docker instance

**Comment by davidlfox** [comment]
yup--thatd work too probably 🤦
