### ISSUE TITLE
Port 8006

### ISSUE THREAD

**Issue by OutOfThisPlanet** [dockur/windows#201]
Might be worth mentioning that the default port of ProxMox's web interface is also port 8006.

If someone runs this container inside of proxmox, this may cause issues with default settings. 

(I will test)

**Comment by DhanrajPatil09** [comment]
Testing it out will provide clarity on any potential issues that might arise. Let me know how it goes!

**Comment by magisk317** [comment]
> Also you can change the portnumber in the compose file real easy to another one, by changing `8006:8006` to `8888:8006` for example.

@kroese By modifying port forwarding, it is indeed possible not to use 8006. If I want to dual-open, that is, run two containers at the same time, there seems to be no way, because internally 8006 has been occupied by the service of the first container.

**Comment by magisk317** [comment]
@kroese 
OK，but why this?

container1:
```
 ports:
      - 8006:8006
```

container2:
```
    ports:
      - 8006:8011
```

container2 log:
```
$ docker-compose down && docker-compose up -d
Stopping windows ... done
Removing windows ... done
Removing network win_default
Creating network "win_default" with the default driver
Creating windows ...
Creating windows ... error

ERROR: for windows  Cannot start service windows: driver failed programming external connectivity on endpoint windows (856fc50fdedabd2a77a7d7ec3d3e4cbb41f9837ff53745417d162f34f64193d5): Bind for 0.0.0.0:8006 failed: port is already allocated

ERROR: for windows  Cannot start service windows: driver failed programming external connectivity on endpoint windows (856fc50fdedabd2a77a7d7ec3d3e4cbb41f9837ff53745417d162f34f64193d5): Bind for 0.0.0.0:8006 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

**Comment by magisk317** [comment]
> @magisk317 You swapped them in the wrong order.. It needs to be `8011:8006` (first one external, second one internal) not `8006:8011`

hahahah，sorry，forgive me I'm a complete newbie when it comes to docker，it's worked，thank you very much，
