### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by lostx754** [dockur/windows#202]
How can I create a certificate for the container using certbot?

**Comment by chminsc** [comment]
> I never used certbot, so I have no idea. The way I would add SSL, is to have a reverse proxy (like Nginx or Caddy) that proxies the http and websocket traffic to port 8006.
> 
> If you use a container like [Nginx Proxy Manager](https://github.com/NginxProxyManager/nginx-proxy-manager) for example, it is very easy to do with just a few clicks.

i did't get it. 
i installed win11 in docker. i can access web through port 8006. but i cann't acess it through nignx reverse proxy from out of my home network. why is that?

the networks works like this: 
url: http://domain:1234, port-forwarded to my own nginx server 4321, and reverse proxy from 4321 to 8006.
i use password auth with nginx. the auth ui comes out when i access this server. but  with error:
504 Gateway Time-out
openresty
