### ISSUE TITLE
QEMU harddisk fail

### ISSUE THREAD

**Issue by TheHippiez** [dockur/windows#204]
windows  | ❯ Extracting Windows 10 bootdisk...
windows  | ❯ Extracting Windows 10 environment...
windows  | ❯ Extracting Windows 10 setup...
windows  | ❯ Extracting Windows 10 image...
windows  | ❯ Adding XML file for automatic installation...
windows  | ❯ Building Windows 10 image...
windows  | ❯ Creating a 64G growable disk image in raw format...
windows  | ❯ Booting Windows using QEMU emulator version 8.2.1 ...
windows  |
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
windows  | BdsDxe: loading Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
windows  | BdsDxe: starting Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
windows  | ❯ ERROR: Forcefully terminating Windows, reason: 0...
windows  |
❯ Shutdown completed!

Trying to start the container on M1, this is my YAML:
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    environment:
      VERSION: "win10"

**Comment by roadkingvrod** [comment]
@kroese sorry, was trying to respond between meetings.  I am running on an x86 chip with Ubuntu running on a VM.  I did set up the storage on an external volume (which could be the problem), so I'll try running without that before commenting more.

**Comment by roadkingvrod** [comment]
The new release fixed it!!!!!!!  Thank you!!!!
