### ISSUE TITLE
ERROR: Forcefully terminating Windows

### ISSUE THREAD

**Issue by zarevskaya** [dockur/windows#211]
Hello,

I'm on a Debian 12 server under Proxmox. KVM is completely functional (really) but I have this error:

❯ Starting Windows for Docker v2.04...

❯ For support visit https://github.com/dockur/windows

❯ Booting Windows using QEMU emulator version 8.2.1 ...

qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000007H:EDX.invtsc [bit 8]

qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000007H:EDX.invtsc [bit 8]

qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000007H:EDX.invtsc [bit 8]

qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000007H:EDX.invtsc [bit 8]

3h3h3hBdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found

BdsDxe: loading Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)

BdsDxe: starting Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)

❯ ERROR: Forcefully terminating Windows, reason: 0...

❯ Shutdown completed!

My Docker-compose:

version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "50G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /srv/appdata/win:/storage
    stop_grace_period: 2m
    restart: on-failure

I don't have much other information to provide unfortunately.

**Comment by zarevskaya** [comment]
What quick answer!

I think my CPU is compatible, Proxmox works fine.

With:

`environment:
      VERSION: "win11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "50G"
      HV: "N"`

my VM crashes.

Any hint?

**Comment by zarevskaya** [comment]
Oh, sorry...

Received SIGTERM, sending ACPI shutdown signal...
❯ Cannot send ACPI signal during Windows setup, aborting...
❯ ERROR: Forcefully terminating Windows, reason: 143...
qemu-system-x86_64: terminating on signal 15 from pid 7 (bash)
❯ Shutdown completed!

**Comment by zarevskaya** [comment]
Who knows why, now it works without deactivating the KVM oO'

After 15 or 16 try.

Sorry for disturbing. And thank you!

**Comment by zarevskaya** [comment]
Ok, thank you very much, I can write my post about your work.

**Comment by matifali** [comment]
I am getting the same error where Dockurr is crashing the whole Ubuntu VM where I am trying this. I loose ssh connection to my VPS when this happens
