### ISSUE TITLE
[Suggestion] Speedup archive.org sources with torrent?

### ISSUE THREAD

**Issue by ShrirajHegde** [dockur/windows#232]
What do you think of speeding up archive.org files with torrent? [aria2](https://aria2.github.io/) supports BitTorrent protocol.

They have excellent amount of seeds, along with web seeds from archive.org mirrors.

Maybe this can be opt-in by a variable. Using this will make archive.org sources the fastest.

**Comment by Gishi1** [comment]
if you add BitTorrent support be sure to add the iso URL as a web seed to keep availability at 100%.

**Comment by ShrirajHegde** [comment]
archive.org usually has webseeds.

But I don't think webseeds are even required for this application, since the files are popular, and I have seen more than 500 active seeds. Even behind a NAT, my internet connection gets saturated pretty quickly. This is a huge contrast to archive.org, which doesn't really seems to have well distributed mirrors. The mirrors seem to be in North America only.
