### ISSUE TITLE
run other OS

### ISSUE THREAD

**Issue by MohMovahedin** [dockur/windows#241]
hello
i used this project and it was so amazing!
but i have a question
is it possible to run another os like any linux distro or any os that provide .iso file ?
and if its possible , how to do that ?
thanks a lot

**Comment by Rasekov** [comment]
Adding to that, since microsoft will be droping active support for WSA it would be really nice to have a clean way to run android inside windows.

**Comment by MohMovahedin** [comment]
thanks a lot
