### ISSUE TITLE
Windows 8.1 error. rs: Assertion `ret < cpu->num_ases && ret >= 0' failed.

### ISSUE THREAD

**Issue by knipper6554** [dockur/windows#255]
Goes through the install fine, up to the point of rebooting, then I get this error.  Happens only on 8.1.  Windows 10 and 11 work fine.

**Comment by knipper6554** [comment]
FYI, I was able to install manually after creating this issue

**Comment by Sandman561** [comment]
Who is this

**Comment by knipper6554** [comment]
Replied via email.
