### ISSUE TITLE
NixOS windows container config on podman backend

### ISSUE THREAD

**Issue by Doosty** [dockur/windows#261]
Hi, just wanted to post my NixOS-podman configs, so they are there if someone searches for nix. I had to use a couple of extra podman args. Love your project, cheers.

```nix
# RDP access: nix run nixpkgs#rdesktop -- -u docker 127.0.0.1:3389
# WEB access: http://127.0.0.1:8006/
{pkgs, ...}: let
  app = "windows";
  dataDir = "/var/lib/${app}";
  ipContainerNetwork = "10.89.53.0/24"; # choose an available network `ip a | grep podman`
  ipContainer1 = "10.89.53.11"; # manual networking is more reliable, trust me
in {
  virtualisation.oci-containers.containers.${app} = {
    image = "docker.io/dockurr/windows:latest"; # <https://hub.docker.com/r/dockurr/windows/tags>
    user = "root:root";
    autoStart = false; # start it when needed with `sudo systemctl start podman-windows.service`
    environment = {
      VERSION = "win11";
      RAM_SIZE = "8G";
      CPU_CORES = "12";
      DISK_SIZE = "100G";
    };
    ports = [
      "127.0.0.1:8006:8006"
      "127.0.0.1:3389:3389/tcp"
      "127.0.0.1:3389:3389/udp"
    ];
    extraOptions = [
      "--device=/dev/kvm"
      "--device=/dev/net/tun"
      "--cap-add=NET_ADMIN"
      "--cap-add=NET_RAW"
      "--network=${app}"
      "--ip=${ipContainer1}"
    ];
    volumes = ["${dataDir}:/storage"];
  };
  systemd.tmpfiles.rules = ["d '${dataDir}' 0700 root root - -"];
  systemd.services."podman-${app}".preStart = ''
    ${pkgs.podman}/bin/podman network exists ${app} || \
    ${pkgs.podman}/bin/podman network create ${app} \
    --subnet=${ipContainerNetwork}
  '';
  networking.firewall.extraCommands = ''
    iptables -A INPUT -p tcp --destination-port 53 -s ${ipContainerNetwork} -j ACCEPT
    iptables -A INPUT -p udp --destination-port 53 -s ${ipContainerNetwork} -j ACCEPT
  '';
  # # if you use nftables
  # networking.firewall.extraInputRules = ''
  #   ip saddr ${ipContainerNetwork} tcp dport 53 accept
  #   ip saddr ${ipContainerNetwork} udp dport 53 accept
  # '';
}
```

**Comment by makergamer** [comment]
For those looking for a classic OCI docker-compose.yml to use with podman, this is not it :-( . It has good info in it, but it is a https://nixos.wiki/wiki/NixOS_Containers file.

**Comment by nyawox** [comment]
sadly not working on nftables, if anyone else are getting `can't initialize iptables table `nat': Table does not exist`, just revert to iptables. You can keep nftables on servers and routers while using iptables on desktop anyways. that's the beauty of NIxOS

**Comment by cguentherTUChemnitz** [comment]
sry to necrobump here, but i think i have some questions related to the nixos configuration:
@Doosty I like the setup of running dockur in nixos to provide locally installed MS-Office via winapps (which provides a flake on their own). But with nixos features of flakes, reproducability and deployment features to different hosts in-mind i would like to hear your thoughts how this might be combined with dockur images here.

When i understand correctly, i would need something like waiting to build the state in the data dir by dockur to finish and deploy it accordingly with nixos itself. I would like when the finished windows image itself can be deployed using existing deployment mechanisms of nixos itself like deploy-rs. Do you maybe have an idea how this would integrate with nixos tooling?

**Comment by Doosty** [comment]
I tried to make winapps work like ~6 months ago, their nix packaging was horribly broken at the time and required lots of path patches to their bash scripts and such, even after i got through that i didnt manage to make it work with freerdp (the remote cmd execution into the windows system just didnt work). In the end i gave up, not sure how the experience is today. I plan to try out https://github.com/TibixDev/winboat since they also seem to have nix in mind, but im not really motivated, these days i just use a plain libvirt vm configured with NixVirt, the usb passthrough is better and i can use `pkgs.virt-manager` and `pkgs.virt-viewer`. 

Here are the nix files for my current dockurr module if anyone is interested, i expanded a bit and added some (probably bad) helper scripts and such. I havent used it in a while but you might get some ideas. For deploying a premade dockurr state i suggest just creating a systemd service that copies over the files, or maybe build a premade nixos image with those files included.

https://gist.github.com/Doosty/2dab302d7445b4fc3b9239958a9fccb0

**Comment by cguentherTUChemnitz** [comment]
Very much thank you for your insights. Nevertheless, it seems in the meantime winapps also improved alot the nixos support. Last week they fixed in my eyes the last visible bug for the nixos side. I am now able to go with your first config here above and use winapps in manual mode just for discovering the apps in the already existing dockur image.
