### ISSUE TITLE
Would it be possible to add a script to create a new docker image that includes Windows?

### ISSUE THREAD

**Issue by ilg-ul** [dockur/windows#264]
I did some tests with a friend, and the resulting Windows was functional. Thank you!

However, if my understanding is right, the provided `dockurr/windows` image installs a fresh Windows each time it is executed, and, without using special volumes, the Windows instance is lost when the docker container is terminated. This is a bit annoying, and perhaps this behaviour should be mentioned/explained in the documentation.

Could you consider a slightly different approach, with a docker script to `docker build` a new image that installs the fresh Windows which later remains persistent in a docker layer and the resulting docker image can be used directly, without having to install Windows at each invocation?

This image can later be also used as a base image for further images, to include more Windows software to be installed, allowing more customisations.

**Comment by ilg-ul** [comment]
> If you remove the --rm flag then it will persist the data.

Can you test this on your machine and provide an example how to invoke docker in subsequent calls? 

In my tests, even without `--rm`, the default script executed by your image re-downloaded the Windows binaries as from scratch.

**Comment by ilg-ul** [comment]
Ok, thank you.

**Comment by ilg-ul** [comment]
However it would still be useful to mention these commands in the README.

**Comment by turbo2ltr** [comment]
Along the same line of questioning, how *does* the container persist data with no volumes configured?  I'm not a docker expert, but I too was expecting the behavior the OP described.  Where is this data stored?
