### ISSUE TITLE
error gathering device information while adding custom device "/dev/kvm"

### ISSUE THREAD

**Issue by pixeline** [dockur/windows#276]
I'm running Docker (version 25.0.3, build 4debf41) on a Apple M1 Macbook Pro (late 2020). 

I get this error message almost immediately:

> Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory

Do I need an extra dependency ? 

Thank you!

**Comment by pixeline** [comment]
That does the trick, thank you!

**Comment by starry-MM** [comment]
> MacOS has no KVM. So the only option is to remove the line with `/dev/kvm` and add this line:
> 
> ```yaml
> environment:
>   KVM: "N"
> ```
> 
> This way the container can be run, but very slow since it will not be accelerated.

very slow indeed. have any way to accelerate？
