### ISSUE TITLE
Unable to access internet in the VM

### ISSUE THREAD

**Issue by hayupadhyaya** [dockur/windows#337]
I created a windows 11 VM with a custom image because for some reason, it would not download automatically. 
I ran the unattended installation, and I am able to access local network but I can't go online. Is there a way to fix this? I am not familiar with docker in general.

**Comment by hayupadhyaya** [comment]
You must have a private ip address. that causes problems. If you want to access it from a public ip then don’t assign a private ip, I don’t know about docker a lot so I can’t help you with how to work with that. Maybe you can create a reverse tunnel on your host and connect to it that way.  You can do it with ssh too or maybe tailscale?
I can look into it more if you can’t figure it out. Let me know, I am available over this weekend.

**Comment by hayupadhyaya** [comment]
Are you using a cloud provider? If so which one?

**Comment by netzih** [comment]
I worked it out.
Was my mistake.
Was using portainer and had to add it to the bridge network and not it's own private one.
