### ISSUE TITLE
"Could not clean disk 0" when mounting usb sticks

### ISSUE THREAD

**Issue by SvenGebert** [dockur/windows#367]
So obviously the container is trying to install the image to my usb stick when mapped like this.
But how do i mount 2 usb sticks - or even one usb stick correctly?
![compose](https://github.com/dockur/windows/assets/82095410/3d39b685-6884-4d1d-9a4c-8d6ea3f43314)
![image](https://github.com/dockur/windows/assets/82095410/7cc6e849-3232-46b1-a4d1-cfec34e4784f)

**Comment by SvenGebert** [comment]
Okay! I'll try that. Thank you for your quick answer!

**Comment by SvenGebert** [comment]
Working! Thanks alot!

**Comment by Tonny24Wang** [comment]
<img width="1142" height="204" alt="Image" src="https://github.com/user-attachments/assets/1ea91a4a-41de-47ad-b274-d4e9c4d2eaee" />
same question!
It works for me.
not plug the usb devicce on the first docker build ,  and plug it later.
