### ISSUE TITLE
Windows freezes at startup

### ISSUE THREAD

**Issue by Yunushan** [dockur/windows#380]
Hello, i checked #353 issue too however,i couldnt able to give proper docker file on my local,could you please check my config

![docker-logs-output-keeps-restarting](https://github.com/dockur/windows/assets/24549832/f3f0a4a0-aa72-4677-9fa2-f2e35d5c9aca)
![docker-logs-error](https://github.com/dockur/windows/assets/24549832/670d2fe0-3c56-4fc8-bd73-061fc005f303)
![pwd-owners-permissions](https://github.com/dockur/windows/assets/24549832/0967fd72-f48d-45fc-a3f5-50ac7da0b529)
![compose yaml-file](https://github.com/dockur/windows/assets/24549832/dea0d667-793f-4a16-b79e-60473ef4e660)

**Comment by Yunushan** [comment]
With default english windows server 2022 iso, 8GB ram ,4 cores cpu and 40g disk size has been granted on compose yaml file by the way.

![error-output](https://github.com/dockur/windows/assets/24549832/fa019f08-6287-4b6a-a8cd-2981315bb68e)

https://www.microsoft.com/en-us/evalcenter/download-windows-server-2022
https://go.microsoft.com/fwlink/p/?LinkID=2195280&clcid=0x409&culture=en-us&country=US

**Comment by sginokj** [comment]
I am trying to boot with tiny10 image and it pulls from the default Win 11 version. I tired downloading the tiny image and renamed as custom.iso and then also it pulls win11 default image.
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: tiny_windows
  volumes:
     - /media/storage/tiny10:/storage
    environment:
      VERSION: "./storage/custom.iso"
    devices:
      - /dev/kvm
environment:
       RAM_SIZE: "4G"
       CPU_CORES: "4"
       DISK_SIZE: "128G"
#    volumes:
#     - /media/storage/tiny10:/storage
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure

![Screenshot from 2024-04-18 11-26-40](https://github.com/dockur/windows/assets/26465521/dd862738-2b42-4f91-9a17-5fadea23f2d9)

**Comment by Yunushan** [comment]
@sginokj  you need to comment # VERSION: "./storage/custom.iso" line

@kroese 

I tried to add that variable too that you said but it still freezes on windows starting screen,i can able to move mouse couple of seconds then it freezed permanently,just something came in to my mind im not sure but  that when i docker compose up -d that custom.iso's md5 is changing from original one,im not sure is it normal or not during starting process but just wanted you to ask.

![folder-files-info](https://github.com/dockur/windows/assets/24549832/3deb2ab1-48de-47fa-8694-bf6b03186366)
![windows-starting-screen-freeze](https://github.com/dockur/windows/assets/24549832/4bb6bac0-e342-4b7d-aa4d-9b1b2cc96fbf)
![docker-logs](https://github.com/dockur/windows/assets/24549832/75766e67-0f30-41bf-8af6-73c29754d7f7)

**Comment by Yunushan** [comment]
I tried with windows server 2022,2019 and windows 11 all of them stucks at the same place,now i also tried with default parameters that you have just said (4GB RAM, 64GB disk, 2 cores) still issue didnt solve yet,unfortunately i'm unable to try with default ones instead of custom file ,because that server can't able to connect properly when it is trying to get iso 

![error](https://github.com/dockur/windows/assets/24549832/c27313f4-43ac-4ecb-8498-673f0e6aa061)

**Comment by Yunushan** [comment]
By the way 2 another questions came in to my mind,i could able to run local iso without any issue with my vmware workstation with amd cpu,but im encountering with that problem vmware esxi under intel cpu could that be the issue too ?

**Comment by Yunushan** [comment]
I had to use under vmware esxi on red hat 7,Thank you for your informative and supportive explanations :)
