### ISSUE TITLE
[Feature]: view-only VNC

### ISSUE THREAD

**Issue by hellodword** [dockur/windows#410]
### Is your proposal related to a problem?

I use dockur in GitHub actions to do some E2E tests, with custom `win11x64.xml`.

I want to observe the status from VNC, while I hope the VNC is view-only because the GitHub actions is public.

### Describe the solution you'd like.

I guess it's possible: 

https://github.com/novnc/noVNC/blob/9a1b1f0d06567739251314a3b67ac5c432ecad47/docs/EMBEDDING.md?plain=1#L56

I hope there will be a new environment variable to control it:

`docker run -e VNC_VIEW_ONLY=yes`

Or simply add a new view-only VNC port

### Describe alternatives you've considered.

_none_

**Comment by kroese** [comment]
This is now implemented, you can set:

```yaml
environment:
  PROTECT: "Y"
  USERNAME: "bill"
  PASSWORD: "gates"
```

to set authentication for the VNC website.
