### ISSUE TITLE
[Question]: How setting KVM=N with docker compose?

### ISSUE THREAD

**Issue by liuyenhui** [dockur/windows#479]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

❯ ERROR: KVM acceleration not available (device file missing), this will cause a major loss of performance.
❯ ERROR: See the FAQ on how to enable it, or continue without KVM by setting KVM=N (not recommended).

How setiting KVM=N?

**Comment by Harm-Nullix** [comment]
https://github.com/dockur/windows/issues/317#issuecomment-2026907815

**Comment by liuyenhui** [comment]
@Harm-Nullix thank you

**Comment by liuyenhui** [comment]
#317
