### ISSUE TITLE
Keyboard layout issue

### ISSUE THREAD

**Issue by jrevillard** [dockur/windows#551]
### Operating system

Ubuntu 24.04 LTS

### Description

Hello,

I'm a French user an try to install Windows using a French configuration.

I'm using this configuration;

```
environment:
      VERSION: "win11"
      LANGUAGE: "French"
      REGION: "fr-FR"
      KEYBOARD: "fr-FR"
```

Everything seems to work well, Windows is in French, I have a French keyboard layout BUT also a ghost US one which make me crazy as this is the one which is selected by default as soon as I connect using RDP. I tried plenty of things to make it disappear but I was not able to do so....

![image](https://github.com/dockur/windows/assets/203909/1e11b121-65b1-49b2-a507-648ce643d236)
![image](https://github.com/dockur/windows/assets/203909/55c3d29e-c808-4cc0-844a-5d1cb58e65a6)

Any help would be greatly appreciate.

By the way, I would prefer to use Tiny11 but I have the same issue after having to manually installed the French language.

Best,
Jerome

### Docker compose

name: "winapps"

services:
  windows:
    image: dockurr/windows
    container_name: windows11
    environment:
      VERSION: "win11"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      LANGUAGE: "French"
      REGION: "fr-FR"
      KEYBOARD: "fr-FR"
    privileged: true
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - ./data:/storage

### Docker log

BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,2C6CCE3E-0CE2-4744-8777-530B5E2E5AB4,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,2C6CCE3E-0CE2-4744-8777-530B5E2E5AB4,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...

**Comment by jrevillard** [comment]
Ehhh you saved my day thanks it works !

I will try to find if I find a FreeeRDP issue already reported. This is anyway strange that this ghost keyboard cannot be removed isn't it (Which is perhapse a Microsoft Win 11 bug...) ?

Best,
Jérôme

**Comment by eylenburg** [comment]
Just wanted to add that the registry method (adding `[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout]
"IgnoreRemoteKeyboardLayout"=dword:00000001`) works - as long as the VM itself has the right keyboard layout in the settings - while the FreeRDP setting (in my case adding `RDP_FLAGS="/kbd:0x00000452"` to winapps.conf) doesn't someone prevents the Windows app from starting.

**Comment by otaolafranc** [comment]
Hello,
i am facing a similar problem but a little bit more strange. I am also using winapps, and in my windows machine i added to the mentionned fix to the reg. I also in windows remove it completly any other keyboards, i only leaved the french one. but when i open the office applications it still in qwerty even after restarting the windows, with the modification of the reg. I really need to get this solve it as if not i can not use it. any idea that could help? 

EDIT: I did not changed the value of the entry on the reg it solved my issue! thaaanks
