### ISSUE TITLE
Windows 10 Setup asking for driver - Synology DSM 7.2.1 DS918+

### ISSUE THREAD

**Issue by Tk95100** [dockur/windows#569]
### Operating system

Synology DSM 7.2.1 DS918+

### Description

I am running docker windows 10 pro from Container Manager -> Projects as docker compose.  It looks like everything is loading until get to setup screen, system is asking for driver!? am I missing something from the yaml file? Thanks.

System is runing on Synology DSM 7.2.1 DS918+
KVM is present (Virtual Machine App was installed)

### Docker compose

version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win10"
      RAM_SIZE: "8G"
      CPU_CORES: "3"
      DISK_SIZE: "60G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
        - ./data:/storage
    network_mode: bridge

### Docker log

<html>
<body>

date | stream | content
-- | -- | --
2024/06/07 05:47:30 | stdout | [2J[01;01H[=3h[2J[01;01H[1;34m❯ [1;36mWindows started succesfully, visit http://localhost:8006/ to view the screen...[0m
2024/06/07 05:47:20 | stdout | BdsDxe: starting Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
2024/06/07 05:47:20 | stdout | BdsDxe: loading Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
2024/06/07 05:47:20 | stdout | [2J[01;01H[=3h[2J[01;01H[2J[01;01H[=3h[2J[01;01H[2J[01;01H[=3h[2J[01;01HBdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
2024/06/07 05:47:19 | stdout | [1;34m❯ [1;36mBooting Windows...[0m
2024/06/07 05:47:19 | stderr | [1;31m❯ Warning: your configured RAM_SIZE of 8 GB is very close to the 8 GB of memory available, please consider a lower value.[0m

</body>
</html>

### Screenshots (optional)

![Win10prodockerError](https://github.com/dockur/windows/assets/102452149/17cc7a26-a15d-4406-987d-a17ca26fe368)
![Log](https://github.com/dockur/windows/assets/102452149/6c77021f-5698-432d-bbf1-f3d93ba6a91f)

**Comment by KEMBL** [comment]
Just a guess, Synology offers an iso image for windows guest systems and it contains drivers which might be what is required in your case.
Though, I do not know how to connect it as a CD-ROM within docur.
