### ISSUE TITLE
Error while starting the container

### ISSUE THREAD

**Issue by cogito-nitin** [dockur/windows#642]
### Operating system

Mac OS 14.2.1 (23C71)

### Description

1. Clone your repo in Mac Local Machine
2. Navigate to windows-master root folder
3. Run docker compose up command 

### Docker compose

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
    devices:
      - /dev/kvm:/dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m

### Docker log

No log file shown after running docker logs windows command

### Screenshots (optional)

<img width="1223" alt="Screenshot 2024-07-11 at 6 19 23 PM" src="https://github.com/dockur/windows/assets/88720951/bf31b873-5b17-49b6-8e18-336fedd2b0e4">

**Comment by deuts** [comment]
Mine is just:
```yml
    devices:
      - /dev/kvm
```

That works for me.
