### ISSUE TITLE
[Question]: RAM_SIZE  less than 1GB

### ISSUE THREAD

**Issue by maxrio** [dockur/windows#657]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

OS : winxp (my VPS only have 1GB )
I set the RAM_SIZE=256M or RAM_SIZE=256MB  ,but it didn't work.

errors:
❯CPU: Intel Xeon CPU E5 2690 v4 | RAM: 0/2 GB | DISK: 5 GB (ext4) | HOST: 4.15.0-20...
❯ ERROR: Your configured RAM_SIZE of 1 GB is too high for the 0 GB of memory available, please set a lower value.

how to set ram size to less 1GB  like 512M or 256M ?

**Comment by maxrio** [comment]
solved;
qemu
-m size  explain
qapi/machine.json：
-------------------------------------------------
1796 ##
1797 # @MemorySizeConfiguration:
1798 #
1799 # Schema for memory size configuration.
1800 #
1801 # @size: memory size in bytes
1802 #
1803 # @max-size: maximum hotpluggable memory size in bytes
1804 #
1805 # @slots: number of available memory 
--------------------------------------------------
so  it use bytes default.    then 256M =256*1024=262144
just set  RAM_SIZE=262144    done

**Comment by lengqie** [comment]
Seems invalid
