### ISSUE TITLE
[Question]:  Is it possible to set environemnt variables IN WINDOWS directly from docker compose?

### ISSUE THREAD

**Issue by Liquidmasl** [dockur/windows#658]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

Hi

I would need some environment variables to be set on the windows VM.
Is there a way for that or do i need to do some scripting?

Thank you!

**Comment by alotufo** [comment]
Not directly from Docker Compose from my understanding, but you can use one of the unattend XML files at the link below. At the end, add a command to create the environment variable. Replace [KEY] and [VALUE].

https://github.com/dockur/windows/tree/master/assets

Line to include in Docker Compose file, replacing the win2016-eval.xml with the one for your operating system:

`-v "./win2016-eval.xml:/custom.xml"`

`<SynchronousCommand wcm:action="add">
    <Order>21</Order>
    <CommandLine>reg.exe add "HKCU\Environment" /v [KEY] /t REG_SZ /d "[VALUE]" /f</CommandLine>
    <Description>Set environment variable</Description>
</SynchronousCommand>`

**Comment by Liquidmasl** [comment]
> Not directly from Docker Compose from my understanding, but you can use one of the unattend XML files at the link below. At the end, add a command to create the environment variable. Replace [KEY] and [VALUE].
> 
> https://github.com/dockur/windows/tree/master/assets
> 
> Line to include in Docker Compose file, replacing the win2016-eval.xml with the one for your operating system:
> 
> `-v "./win2016-eval.xml:/custom.xml"`
> 
> `<SynchronousCommand wcm:action="add"> <Order>21</Order> <CommandLine>reg.exe add "HKCU\Environment" /v [KEY] /t REG_SZ /d "[VALUE]" /f</CommandLine> <Description>Set environment variable</Description> </SynchronousCommand>`

Thank you!
In the end I just mounted a .env file into the container and at the start of my code i load this file to set the variables. 
but I will be looking at your suggestion!
