### ISSUE TITLE
fresh windows install

### ISSUE THREAD

**Issue by slaygirlz** [dockur/windows#701]
### Operating system

ubuntu 22.04.4

### Description

installed windows freshly. installed updates. rebooted. install and rebooted. enter recovery mode check the c disk GONE

### Docker compose

version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows-sharedpc 
    devices:
      - /dev/kvm
    volumes:
      - /docker/windows-sharedpc/data:/storage
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389
    environment:
      DISK_SIZE: 240G
      RAM_SIZE: 32G
      CPU_CORES: 5
      USERNAME: "slaygirl"
      PASSWORD: "aaaaaaaaaaaaaaaaaa."
      VERSION: "win11"
    stop_grace_period: 2m
    restart: unless-stopped 
    network_mode: bridge 

### Docker log

4620288K ........ ........ ........ ........ 69% 62.9M 34s
4653056K ........ ........ ........ ........ 70% 62.8M 34s
4685824K ........ ........ ........ ........ 70% 63.1M 33s
4718592K ........ ........ ........ ........ 71% 63.1M 33s
4751360K ........ ........ ........ ........ 71% 62.8M 32s
4784128K ........ ........ ........ ........ 72% 63.2M 31s
4816896K ........ ........ ........ ........ 72% 63.0M 31s
4849664K ........ ........ ........ ........ 73% 63.0M 30s
4882432K ........ ........ ........ ........ 73% 63.1M 30s
4915200K ........ ........ ........ ........ 74% 62.9M 29s
4947968K ........ ........ ........ ........ 74% 63.7M 28s
4980736K ........ ........ ........ ........ 75% 64.7M 28s
5013504K ........ ........ ........ ........ 75% 65.4M 27s
5046272K ........ ........ ........ ........ 76% 65.7M 27s
5079040K ........ ........ ........ ........ 76% 65.7M 26s
5111808K ........ ........ ........ ........ 77% 66.8M 26s
5144576K ........ ........ ........ ........ 77% 67.6M 25s
5177344K ........ ........ ........ ........ 78% 67.9M 24s
5210112K ........ ........ ........ ........ 78% 68.3M 24s
5242880K ........ ........ ........ ........ 79% 69.9M 23s
5275648K ........ ........ ........ ........ 79% 71.2M 23s
5308416K ........ ........ ........ ........ 80% 72.8M 22s
5341184K ........ ........ ........ ........ 80% 74.7M 22s
5373952K ........ ........ ........ ........ 81% 76.4M 21s
5406720K ........ ........ ........ ........ 81% 78.5M 20s
5439488K ........ ........ ........ ........ 82% 81.0M 20s
5472256K ........ ........ ........ ........ 82% 83.0M 19s
5505024K ........ ........ ........ ........ 83% 85.7M 19s
5537792K ........ ........ ........ ........ 83% 88.2M 18s
5570560K ........ ........ ........ ........ 84% 91.0M 17s
5603328K ........ ........ ........ ........ 84% 93.6M 17s
5636096K ........ ........ ........ ........ 85% 96.5M 16s
5668864K ........ ........ ........ ........ 85% 70.8M 16s
5701632K ........ ........ ........ ........ 86% 50.5M 15s
5734400K ........ ........ ........ ........ 86% 52.7M 15s
5767168K ........ ........ ........ ........ 87% 53.9M 14s
5799936K ........ ........ ........ ........ 87% 55.6M 14s
5832704K ........ ........ ........ ........ 88% 56.2M 13s
5865472K ........ ........ ........ ........ 88% 57.6M 13s
5898240K ........ ........ ........ ........ 89% 57.9M 12s
5931008K ........ ........ ........ ........ 89% 58.2M 11s
5963776K ........ ........ ........ ........ 90% 58.3M 11s
5996544K ........ ........ ........ ........ 90% 58.4M 10s
6029312K ........ ........ ........ ........ 91% 58.6M 10s
6062080K ........ ........ ........ ........ 91% 58.6M 9s
6094848K ........ ........ ........ ........ 92% 58.4M 9s
6127616K ........ ........ ........ ........ 92% 58.7M 8s
6160384K ........ ........ ........ ........ 93% 58.5M 8s
6193152K ........ ........ ........ ........ 93% 58.7M 7s
6225920K ........ ........ ........ ........ 94% 60.0M 7s
6258688K ........ ........ ........ ........ 94% 60.4M 6s
6291456K ........ ........ ........ ........ 95% 60.5M 5s
6324224K ........ ........ ........ ........ 95% 61.3M 5s
6356992K ........ ........ ........ ........ 96% 62.2M 4s
6389760K ........ ........ ........ ........ 96% 63.1M 4s
6422528K ........ ........ ........ ........ 97% 62.8M 3s
6455296K ........ ........ ........ ........ 97% 60.0M 3s
6488064K ........ ........ ........ ........ 98% 46.9M 2s
6520832K ........ ........ ........ ........ 98% 50.5M 2s
6553600K ........ ........ ........ ........ 98% 53.4M 1s
6586368K ........ ........ ........ ........ 99% 55.5M 1s
6619136K ........ ........ ........ ........ 99% 57.4M 0s
6651904K .                                  100% 60.4M=1m50s
❯ Extracting Windows 11 image...
❯ Adding drivers to image...
❯ Adding win11x64.xml for automatic installation...
❯ Building Windows 11 image...
❯ Creating a 240G growable disk image in raw format...
❯ Booting Windows using QEMU v9.0.2...
3h3h3hBdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A131E1C7-49AA-414E-B3E8-FB789F980C93,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/c3a27364-ee78-40e9-8951-19b762528cba)
the updates installing
![image](https://github.com/user-attachments/assets/5a762d0d-9989-482d-9160-9a6b921246a6)

**Comment by slaygirlz** [comment]
update!

manually installing windows fixed this huge issue

**Comment by slaygirlz** [comment]
another update the same behaver happened again

**Comment by slaygirlz** [comment]
just 2 reboots on the host and 3 container stop and restart JUST Kills windows

**Comment by slaygirlz** [comment]
any updates?

**Comment by 1tbfree** [comment]
i rarely use docker but i dont know

**Comment by 1tbfree** [comment]
i havent rebooted dockurr windows

**Comment by 1tbfree** [comment]
but does it have persistent disk/can make it somehow

**Comment by sedlacl** [comment]
I can confirm this as repeatable issue, it doesnt matter if is installed manually or not. After windows update is C:\ gone:(

**Comment by 1tbfree** [comment]
i'm gonna look in this issue

**Comment by 1tbfree** [comment]
maybe, try doing volumes:
  - /var/win:/storage

**Comment by slaygirlz** [comment]
https://github.com/dockur/windows/issues/705
