### ISSUE TITLE
[Feature]: Can't play sound?  Could be support sound?

### ISSUE THREAD

**Issue by guozanhua218** [dockur/windows#702]
### Is your proposal related to a problem?

Hope to play sound correct

### Describe the solution you'd like.

Hope to play sound correct

### Describe alternatives you've considered.

Hope to play sound correct

**Comment by MMaaxx3253** [comment]
no sound with noVNC
Yes sound with RDP
Use RDP

**Comment by kroese** [comment]
Audio streaming in the web viewer is now implemented in the latest image! Only thing you have to do is set `AUDIO=Y` in the compose file.
