### ISSUE TITLE
Unlocking locked user account

### ISSUE THREAD

**Issue by marcschroeder** [dockur/windows#704]
### Operating system

Windows 11

### Description

We have a working installation of a dockur Windows 11 image.
Unfortantly, we got the user account locked out.
Is there a way to unlock the account again?
E.g. by accessing the windows command line?

### Docker compose

docker run -it -d --restart=always -p 3389/tcp -p 3389/udp --device=/dev/kvm -e RAM_SIZE='8G' -e CPU_CORES='4' -e VERSION='win11' -v /data/storage --stop-timeout 120 --cap-add NET_ADMIN dockurr/windows

### Docker log

BdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,70D23821-F9E4-4A85-B263-74DEE383D623,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0003 "Windows Boot Manager" from HD(1,GPT,70D23821-F9E4-4A85-B263-74DEE383D623,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/2070b589-c84a-4988-8416-615138a654a5)

**Comment by MMaaxx3253** [comment]
try renaming account, re-enabling RDP, reinstall (as a last resort)

**Comment by marcschroeder** [comment]
I haven't found a solution to this issue.
However the account is being unlocked automatically after some time.
So disabling the RDP / VNC access and keeping the machine running without internet access should solve the issue after some time.
