### ISSUE TITLE
After 2 reboots Windows does not start anymore

### ISSUE THREAD

**Issue by buckbaggen** [dockur/windows#705]
### Operating system

Host: Ubuntu 24.04 LTS Container: Windows11

### Description

I use the container with the compose file provided in this post, it starts, works smooth and everything works. But after 2 reboots The container crashes (exited with code 0) and when i try again i get in recovery mode, 

The log in docker says nothing, when the container crashes it says 'Shutdown complete!' and when it starts correctly but gets in recovery mode the log says 'The default notice that you can conncet to ip blabla on port 8006' . 

### Docker compose

services:
  windows:
    image: dockurr/windows
    container_name: windows11
    environment:
      VERSION: "win11"
      LANGUAGE: "Dutch"
      KEYBOARD: "en-US"
      REGION: "nl-NL"
      DISK_SIZE: "128G"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
      DHCP: "Y"
      MANUAL: "Y"
    volumes:
      - windows11:/storage
    devices:
      - /dev/kvm
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    networks:
      vlan:
        ipv4_address: 10.0.1.6
    ports:
      - 8006:8006 
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
volumes:
  windows11:
networks:
  vlan:
    external: true

### Docker log

nothing

**Comment by slaygirlz** [comment]
i have this issue aswell https://github.com/dockur/windows/issues/701

**Comment by slaygirlz** [comment]
like the WHOLE C:\ Is gone like do a list disk nothing is their

**Comment by sedlacl** [comment]
Well, I found a strange answer somewhere on qemu forums: https://forum.proxmox.com/threads/new-windows-11-vm-fails-boot-after-update.137543/

you need to add 
ARGUMENTS: "-cpu qemu64,+aes"  (change cpu type) and it start to work back again...

**Comment by sedlacl** [comment]
I found solution: -cpu host,-vmx

**Comment by slaygirlz** [comment]
perfect, how do you do it in a docker compose format

**Comment by buckbaggen** [comment]
Indeed, what do i need to put in the compose file?

> I found solution: -cpu host,-vmx

**Comment by sedlacl** [comment]
> Indeed, what do i need to put in the compose file?
> 
> > I found solution: -cpu host,-vmx

`environment:
  - ARGUMENTS: “-cpu host,-vmx”`

**Comment by buckbaggen** [comment]
Thanks! This fixed my VM and now it starts normaly! 

I don't understand why turning off VMX fixes the issue (because my cpu, intel i5 13500) supports VMX and is enabled in the bios.

But i'm happy it works now! My compose file at the moment:

services:
  windows:
    image: dockurr/windows
    container_name: windows11
    environment:
      ARGUMENTS: "-cpu host,-vmx"
      VERSION: "win11"
      LANGUAGE: "Dutch"
      KEYBOARD: "en-US"
      DISK_SIZE: "128G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DHCP: "Y"
      MANUAL: "Y"
    volumes:
      - windows11:/storage
    devices:
      - /dev/kvm
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    networks:
      vlan:
        ipv4_address: 10.0.1.6
    ports:
      - 8006:8006 #Alleen nodig voor te benaderen via browser, eenmaal mstsc ingesteld, deze uitschakelen door een # ervoor te zetten
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m

volumes:
  windows11:
networks:
  vlan:
    external: true



#Run op de dockerhost onderstaand commando om het vlan aan te maken(vanzelfsprekend zonder de hastags!):
#sudo docker network create -d macvlan \
    #--subnet=10.0.1.0/24 \
    #--gateway=10.0.1.1 \
    #--ip-range=10.0.1.6/32 \
    #-o parent=enp3s0 vlan

**Comment by slaygirlz** [comment]
well done everyone for a fix to change a simple argument, hopefully a real fix for everyone is out soon so no one deals with this. I had to cancel a project because of this issue and moved to a real pc lol

**Comment by phanirithvij** [comment]
Tell me if I am wrong, if I enable VMX I can't use this project, because of this reboot issue.
