### ISSUE TITLE
[Question]: Would I be able to host the Docker image on my own domain

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [dockur/windows#712]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

I'd like to know if it's possible to use my own domain for hosting instead of using [port 8080](localhost:8080).

**Comment by needhamgary** [comment]
Yes this is possible. If you use cloudflare,  create an A or AAAA record that points to your public ip and turn off proxy and hit save. Now on your router,  forward the port 3389 from the machine ip that's running the container. Voila, connect to that dns record
