### ISSUE TITLE
[Question]: Why does the container still take space even if it gets force turned off or crashes?

### ISSUE THREAD

**Issue by 1tbfree** [dockur/windows#724]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

It is a question not bug btw

**Comment by LessPlum3393** [comment]
When the VM is turned off and then turned on again, Windows gets reinstalled. To remove the VM, you need to locate and delete a specific file.

**Comment by 1tbfree** [comment]
I found the command. You have to prune all containers (google how to do it)
