### ISSUE TITLE
[Question]: how can i build it and rerun it?

### ISSUE THREAD

**Issue by Gedankenn** [dockur/windows#731]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

it keeps redownloading the windows image, someone please know how to do it? im needing help with it.

**Comment by marcopaganini** [comment]
You need to define a "storage" location in your `docker-compose.yml` file. Basically:

```
volumes:
  - LOCAL_DIRETORY_TO_HOLD_IMAGE:/storage
```

With this, the windows image will be created on your local drive, instead of inside the container. Next time you run it, it will detect an installation and just start it.

**Comment by Gedankenn** [comment]
ohhh, thanks, really thanks, i added the image location, but not the storage.

**Comment by Gedankenn** [comment]
@marcopaganini i'm still with trouble to run the proper commands and stuff, you know any documentation on docker and how to propper build and run things?, i found lots of tutorials but all the commands the guys use does'nt run.
