### ISSUE TITLE
UEFI boot issue while using a custom ISO

### ISSUE THREAD

**Issue by denny0810** [dockur/windows#747]
### Operating system

windows 10 LTSB 2016 x86

### Description

The ISO file is win10 LTSB2016_x86 system. iso file can be extracted in the container but the installation stopped at the booting stage. see the snapshot below.  Both v3.12 and latest v3.17 version were failed due to the same issue. 
![PixPin_2024-09-21_20-52-38](https://github.com/user-attachments/assets/7c4fbea7-250f-4fa8-9c37-976c4e3ec58d)

### Docker compose

version: "3"
services:
  windows:
    image: dockurr/windows:3.12
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    networks:
      - bridge1
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /opt/docker/docker-win/storage:/storage
      - /opt/docker/docker-win/shared/:/shared
      - /opt/docker/docker-win/shared/ltsb2016.iso:/custom.iso
    environment:
      MANUAL: "N"
      RAM_SIZE: "512M"
      CPU_CORES: "1"
      DISK_SIZE: "6G"
      stop_grace_period: 2m
    restart: unless-stopped
# limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m
networks:
  bridge1:
    external: true    

### Docker log

UEFI Interactive Shell v2.2
EDK II
UEFI v2.70 (Debian distribution of EDK II, 0x00010000)
Mapping table
      FS0: Alias(s):CD0a0b:;BLK2:
          PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)/CDROM(0x1)
      FS1: Alias(s):F0a0:;BLK3:
          PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)/VenMedia(C5BD4D42-1A76-4996-8956-73CDA326CD0A)
     BLK4: Alias(s):
          PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)
     BLK0: Alias(s):
          PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
     BLK1: Alias(s):
          PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)/CDROM(0x0)
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...

**Comment by denny0810** [comment]
> Do you have a download link to the .ISO?

https://www.123684.com/s/7zenjv-A147d
The link is avalialbe within the next 7 days.

**Comment by denny0810** [comment]
> I cannot download it, because it needs payment or an account. But I see from the filename that it is for the x86 (32-bits) version of Windows 10. And this container only supports the x64 (64-bit) version of Windows 10. So even if the ISO would boot, it would still fail to install because I don't include any drivers and xml file for 32-bits Windows.

oh~, I see. is it possible to add the feature to support 32-bit system?

**Comment by denny0810** [comment]
> @denny0810 I already support x86 for Windows XP/Vista/7 but not for Windows 10, because its a lot of extra work and not many people are using the x86 edition of Win10. Why cant you use the normal Win10?
I
The docker-win is running on openwrt that I try to let the windows system use as less ram as possible.  I may can try the 32-bit win7. 
Thanks.

**Comment by bogao** [comment]
@kroese Actually a lot of people, including myself, are trying to install Windows 10 x86, due to the reason that we are trying to test the software we develop on different platforms and Windows 10 x86 is a missing scenario if we do not cover it. So, if possible, would you be pleased to add Windows 10 x86 also for our sake? Thanks in advance!
