### ISSUE TITLE
[Feature]: Add IOT 

### ISSUE THREAD

**Issue by jinkazph** [dockur/windows#838]
### Is your proposal related to a problem?

Please add Windows 11 IoT LTSC

### Describe the solution you'd like.

Please add Windows 11 IoT LTSC

### Describe alternatives you've considered.

Please add Windows 11 IoT LTSC

**Comment by rainforest-9716** [comment]
Which driver should I install during the installation process?
it won't automatically select the driver for me, and it looks like I choose the wrong driver.
![image](https://github.com/user-attachments/assets/bf81fc70-01fe-43a1-93aa-1c2aead3f818)
