### ISSUE TITLE
Passing environment variables from Docker container to Windows

### ISSUE THREAD

**Issue by lcax200000** [dockur/windows#843]
### Operating system

ubuntu 22.04

### Description

I need to pass some environment variables from the Docker container to the Windows  inside the container.
What should I do?

### Docker compose

none

### Docker log

none

**Comment by dengniqiu** [comment]
There is a configuration in the file to modify the configuration of the data file to the local file (but I can't find which directory the data folder is mapped to in the system),There is also a way,Enter the file directory to use the temporary php website php -S 127.0.0.1:xxx Enter the system to access the host IP+ port to download,If you want to permanently access the website, you can try to use the Alist network disk,Mount the directory,You windows want to upload content directly to access the network disk, The network disk also supports uploading.

**Comment by lcax200000** [comment]
It has been solved by install.bat

**Comment by Eric-3A** [comment]
> It has been solved by install.bat
If you want to pass variables into windows, how do you write them in the install.bat file, right
environment:
ENV1: "TEST"

**Comment by Eric-3A** [comment]
> @Eric-3A `setx variable value /m`
My requirement is to load environment variables every time the system starts up, not only when the system is newly installed, because I am using persistent storage, how do I implement loading environment variables every time the system starts up

**Comment by Eric-3A** [comment]
> @Eric-3A See https://www.howtogeek.com/208224/how-to-add-a-program-to-startup-in-windows/ for a couple of methods to run a program at startup. You can just create a registry key for example.

It is ok to start some programs on the boot. I want to specify environment variables into the container when starting the windows container. My windows container uses persistent storage and does not need to install the system, so install.bat does not run on the installed system
