### ISSUE TITLE
[Question]: Difference in the images used vs Microsoft officials

### ISSUE THREAD

**Issue by jamar1909** [dockur/windows#871]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

This is a follow on to #857 if the images being used are not the official Microsoft ones, what is different about them, if any?

**Comment by elleparker** [comment]
yes,
