### ISSUE TITLE
[Feature]: Use only container instead external storage (volume or host mapping)

### ISSUE THREAD

**Issue by Krzysztof318** [dockur/windows#880]
### Is your proposal related to a problem?

Currently each container uses docker volumes or we can optionally map it to host path.

### Describe the solution you'd like.

Allowing disable external storage and store all windows files with container. Of course it will cause containers will very big, but then we can easly use docker commit to create container image as checkpoint purpose. Currently for using this for testing software is a bit inconvenient because everytime I create new fresh container for testing it reinstall whole system. If I can create custom container image after installation with docket commit it should be much faster to create new fresh containers for software testing.

### Describe alternatives you've considered.

Manually backup docker volumes.

**Comment by Krzysztof318** [comment]
I will try but honestly I don't see change in the code repo or I am just blind ;) I tried to search for usage of this envirenent in code but I got nothing.

**Comment by Krzysztof318** [comment]
It works but commiting with docker is almost impossible, hangs on commit command, anyway your path works, just docker has a problem with commit huge image about 64gb.

**Comment by Krzysztof318** [comment]
@kroese Could you also disable creating empty volume and remove iso file after installation?

**Comment by Krzysztof318** [comment]
I am not docker and linux speciallist but image from container shouldn't be smaller? data.img is growable disk so, why it takes full size when docker commit?

**Comment by xlazom00** [comment]
Something like this will be also fine for docker image layers
qemu support disk snapshots
https://kashyapc.fedorapeople.org/virt/lc-2012/snapshots-handout.html

**Comment by Krzysztof318** [comment]
Implemented
