### ISSUE TITLE
How k8s to fix BdsDxe: failed to load Boot0002 ?

### ISSUE THREAD

**Issue by cc901109** [dockur/windows#889]
### Operating system

ubuntu 22.04

### Description

I used kubernetes.yml to create,and I have this problem,how can I fix it?
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)

### Docker compose

I used k8s and I follow kubernetes.yml to do it

### Docker log

BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)

**Comment by cc901109** [comment]
Now, I have another problem - when QWMU run, I choose the esc button and it request the error 'BdsDxe: failed to load Boot0002'
![error](https://github.com/user-attachments/assets/5e5ebd27-d52d-4a2b-b7b7-f8632268c47c)

**Comment by cc901109** [comment]
@kroese Thanks a lot.
So, how can I do when it have the message 'cannot boot from the harddrive' ?

**Comment by cc901109** [comment]
@kroese 
I see that message when the the container run, I wait about 10 min it will show me dosn't connect to server
![QEMU](https://github.com/user-attachments/assets/ccb8a955-5e9a-4ff2-af23-40e1c29f3637)

**Comment by cc901109** [comment]
![image](https://github.com/user-attachments/assets/65fa3793-6ee8-413f-9f3a-29056c708273)

**Comment by KovalenkoDV** [comment]
Has someone found a solution to this stupid problem?!
