### ISSUE TITLE
Working Setup in Proxmox LXC

### ISSUE THREAD

**Issue by foofus-sph1nx** [dockur/windows#899]
### Operating system

Proxmox

### Description

NOT AN ISSUE!

Thank you for the great work on this project. This really enhances what I can do with my limited resourced proxmox server. Had to jump through a bunch of hoops to get it working and so writing down what worked for me so that it helps others trying to get this project setup. These are the steps that were taken.

1. Setup Ubuntu (or distro of choice) in a privileged LXC container 
2. Next configure the container by navigating to the `conf` file and adding the following lines (usual location is /etc/<whatever-name/lxc)
```
lxc.apparmor.profile: unconfined
lxc.cgroup.devices: a
lxc.cap.drop: 
lxc.cgroup2.devices.allow: c 10:232 rwm
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.cgroup2.devices.allow: c *:* rwm
lxc.mount.entry: /dev/net dev/net none bind,create=dir
lxc.mount.entry: /dev/kvm dev/kvm none bind,optional,create=file
```
3. Restart container after making these changes
4. Next install portainer (or choice of docker management software) and then create a stack. The exact compose file can be found below.
5. I have added a macvlan and enabled DHCP so that the Windows system gets an IP from the router.
6. The VNC connection IP is whatever x.x.x.x is set to while the RDP access is via the IP that the router provides.
7. The same setup also works to get MacOS setup in a separate container.

Some of the settings in the docker compose file could very well be extraneous since I was trying to get it to work with trial and error and with no expertise in docker whatsoever.

Hope this helps someone!

### Docker compose

services:
  windows:
    image: dockurr/windows
    container_name: windows
    networks:
      macvlan1:
        ipv4_address: x.x.x.x
    privileged: true
    environment:
      VERSION: "10"
      DHCP: "Y"
    devices:
      - /dev/kvm
      - /dev/vhost-net
    volumes:
      - /home/storage:/data
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    sysctls:
      - net.ipv4.ip_forward=1
networks:
  macvlan1:
     external: true

### Docker log

If everything works the logs should look like this

❯ Booting Windows using QEMU v9.1.0...

3h3h3hBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,F657FFC7-14EA-4062-BCAE-5B2A7EDB4CC8,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi

BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,F657FFC7-14EA-4062-BCAE-5B2A7EDB4CC8,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi

❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...

**Comment by verydemo** [comment]
/dev/vhost-net not found

**Comment by spacex-3** [comment]
> /dev/vhost-net not found

maybe you can try to add this to the lxc conf
lxc.mount.entry: /dev/vhost-net dev/vhost-net none bind,create=file 0 0
