### ISSUE TITLE
No second disk while using path:/storage2

### ISSUE THREAD

**Issue by sternensim** [dockur/windows#906]
### Operating system

Ubuntu 24.04.1 LTS x86_64

### Description

When i try to generate a second disk it will still not be available in Windows. Normal passthrough to the host.lan Network Drive work fine.
I reinstalled the container but the issue persits. 
Thank you for your help!

### Docker compose

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      REGION: "de-DE"
      KEYBOARD: "de-DE"
      DISK2_SIZE: "64G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
    - /path/to/file1:/data
    - /path/to/file2:/storage2

### Docker log

❯ Starting Windows for Docker v4.04...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Core TM i7 3770K | RAM: 16/32 GB | DISK: 446 GB (ext4) | KERNEL: 6.8.0-48...
❯ Booting Windows using QEMU v9.1.1...
3h3h3hBdsDxe: loading Boot0005 "Windows Boot Manager" from HD(1,GPT,C81C6034-563E-4B1F-AC21-CE67CE289FFF,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0005 "Windows Boot Manager" from HD(1,GPT,C81C6034-563E-4B1F-AC21-CE67CE289FFF,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/d159bfcc-3d53-48c3-ad5c-910a2ce80e7b)

**Comment by sternensim** [comment]
I have changed it to a directory with the same result.

**Comment by sternensim** [comment]
Issue closed, i missunderstood how you can get the second disk. I found it now in the Diskmanager. Its not a live link like the network device but a second "real" disk. My mistake

**Comment by cc901109** [comment]
@sternensim Hello,I have the same question. What do you do for this?

**Comment by republicandaddy** [comment]
I've been looking through the issues section and this seems to be the closest topic to my question, so I thought I'd try here instead of opening a new thread.  

Is it possible to mount a directory on the host as a drive (not mapped network drive) in the container?  Basically I'd like the directory on the host to appear as a Drive D: and exist in the drive manager.

**Comment by ThailerL** [comment]
@republicandaddy what I did was use Dokany to mirror the network share to a drive https://github.com/dokan-dev/dokany/wiki/Use-Mirror-example. I set up the command as a service using NSSM so that it runs on boot.
