### ISSUE TITLE
Audio device not found

### ISSUE THREAD

**Issue by mihussein** [dockur/windows#909]
### Operating system

Arch linux

### Description

audio device and maybe other devices also not found in windows xp to play media

### Docker compose

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "xp"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - ./data:/storage

### Docker log

null

### Screenshots (optional)

![screenshot_2024-11-17-145151](https://github.com/user-attachments/assets/e095f359-ce64-47d5-9a61-af84da4872ff)
![screenshot_2024-11-17-153631](https://github.com/user-attachments/assets/2812f21d-a8ee-4f5d-9b18-959a0eadc2e6)

**Comment by kroese** [comment]
Audio streaming in the web viewer is now implemented in the latest image! As this adds a soundcard to the machine, it might solve your original issue too. Only thing you have to do is set `AUDIO=Y` in the compose file.
