### ISSUE TITLE
[Bug]: BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found

### ISSUE THREAD

**Issue by Czj1997-02** [dockur/windows#942]
### Operating system

Ubuntu20.04

### Description

BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found

### Docker compose

```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "64G"
      USERNAME: "root"
      PASSWORD: "root"
      LANGUAGE: "Chinese"
      # 设置KVM为N，表示不使用KVM加速
      KVM: "N"
    volumes:
      - /opt/windows/storage:/storage
      - /opt/windows/data:/data
    # 设置 privileged 允许访问所有设备
    privileged: true
    # devices:
      # ls -l /dev
      # ls -l /dev | grep kvm
      # sudo chmod 666 /dev/udmabuf 
      # - /dev/udmabuf:/dev/udmabuf
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
```

### Docker log

```
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
windows  | BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
windows  | BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
```

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/4301c7f7-7889-4644-bc18-d0b3593d0a00)

**Comment by sladiri** [comment]
I get the same error with `VERSION=11` but `VERSION=10` works. With Windows 11, Windows setup stops asking for a driver for the hard drive. No hard drives are available for installaion.

**Comment by N0Klu3** [comment]
@kroese I am getting the exact same on an unRAID Host.
Fresh install as of a few mins ago using the Win 11 image as well...

**Comment by N0Klu3** [comment]
This was my compose

`services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      RAM_SIZE: "24G"
      CPU_CORES: "8"
      REGION: "en-GB"
      KEYBOARD: "en-GB"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/user/appdata/windows/storage:/storage
      - /mnt/user/appdata/windows/shared:/data
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    network_mode: "bridge" `

**Comment by Czj1997-02** [comment]
@sladiri Thanks u，yes，`VERSION=10` is ok

**Comment by sladiri** [comment]
> @sladiri Then you are using an old version of the container, that problem was fixed a few versions ago.

Pulled the new image (I always forget) and it works now, thank you.

@Czj1997-02 You can pull the latest image, Windows setup should be fixed: `podman pull docker.io/dockurr/windows`.

**Comment by jerryzhcz** [comment]
yes, VERSION=10 is ok
