### ISSUE TITLE
[Bug]: host.lan没有，并且\\20.20.20.1连接失败

### ISSUE THREAD

**Issue by liuyang77886** [dockur/windows#943]
### Operating system

centos8.5

### Description

使用官方镜像en_windows_7_enterprise_with_sp1_x64_dvd_u_677651.iso和cn_windows_7_ultimate_sp1_x64_dvd_677408.iso安装的vin7都没有文件共享

![1733194663367](https://github.com/user-attachments/assets/6a2f8424-99a9-4dfd-900d-b5bad816354d)

### Docker compose

version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    privileged: true
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 28006:8006
      - 23389:3389/tcp
      - 23389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    environment:
      VERSION: "7e"
      MANUAL: "Y"
      LANGUAGE: "Chinese"
      RAM_SIZE: "16G"
      CPU_CORES: "16"
      DISK_SIZE: "1024G"
      USERNAME: "root"
      PASSWORD: "123456"
    volumes:
      - /data/windata:/storage
      - /home/data:/data
      - /home/soft/cn_windows_7_ultimate_sp1_x64_dvd_677408.iso:/custom.iso
    networks:
      winlynet:
        ipv4_address: 172.16.111.196
networks:
  winlynet:
    external: true

### Docker log

windows  | iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
windows  | Perhaps iptables or your kernel needs to be upgraded.
windows  | ❯ ERROR: The 'ip_tables' kernel module is not loaded. Try this command: sudo modprobe ip_tables iptable_nat
windows  | ❯ Warning: falling back to usermode networking! Performance will be bad and port mapping will not work.

❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...

**Comment by golvellius** [comment]
Hi .. 
I am running the system perfect, but suddenly i have lost host.lan in windows11. When i boot the docker container i have the next error:

ERROR: The 'tun" kernel module is not available. Try this command: 'sudo modprobe tun' or run the container with 'privileged: true' .....

I have done modprobe tun command with no luck. To enablehost.lan inside windows 11, now i have to modify docker-compose and add privileged: true... 

Maybe something regarding a pull docker upgrade ( now using Docker v4.05) or a system upgrade ?

**Comment by golvellius** [comment]
Hi .. 

Working adding /dev/net/tun ...
What i do not understand is that before it was working ... and suddenly stops working .. 

Thanks ..

**Comment by liuyang77886** [comment]
sudo modprobe ip_tables iptable_nat
