### ISSUE TITLE
Automatic shutdown of container after an hour

### ISSUE THREAD

**Issue by recluzegeek** [dockur/windows#983]
### Operating system

Windows 11

### Description

Container shutdown automatically after an hour from the launch. I've plenty of system resources 64GB RAM, RTX 4080 and Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz   3.20 GHz  (2 processors). I've monitored the system whether the shutdown is caused by the lack of resources but this is not the case.

### Docker compose

```bash
services:
  windows:
    image: dockurr/windows
    container_name: windows11
    environment:
      VERSION: "10l"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      USERNAME: "bill"
      PASSWORD: "gates"
      HV: "N"
      BOOT_MODE: "windows_plain"
    volumes:
      - E:\containers\dockur-windows\win10ltsc:/storage
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 33389:3389/tcp
      - 33389:3389/udp
    stop_grace_period: 2m
 ```

### Docker log

❯ Starting Windows for Docker v4.06...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Xeon E5 2667 v3 | RAM: 30/32 GB | DISK: 480 GB (v9fs) | KERNEL: 5.15.167.4-microsoft-standard-WSL2...

❯ Warning: unexpected clocksource: hyperv_clocksource_tsc_page
❯ Booting Windows using QEMU v9.1.1...
BdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
❯ Shutdown completed!
❯ Starting Windows for Docker v4.06...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Xeon E5 2667 v3 | RAM: 30/32 GB | DISK: 478 GB (v9fs) | KERNEL: 5.15.167.4-microsoft-standard-WSL2...

❯ Warning: unexpected clocksource: hyperv_clocksource_tsc_page
❯ Booting Windows using QEMU v9.1.1...
BdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,E261DCC3-F035-4749-98A5-CF58E89315B0,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0003 "Windows Boot Manager" from HD(1,GPT,E261DCC3-F035-4749-98A5-CF58E89315B0,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
❯ Received SIGTERM, sending ACPI shutdown signal...
❯ Waiting for Windows to shutdown... (1/110)
❯ Waiting for Windows to shutdown... (2/110)
❯ Waiting for Windows to shutdown... (3/110)
❯ Shutdown completed!
❯ Starting Windows for Docker v4.06...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Xeon E5 2667 v3 | RAM: 30/32 GB | DISK: 471 GB (v9fs) | KERNEL: 5.15.167.4-microsoft-standard-WSL2...

❯ Warning: unexpected clocksource: hyperv_clocksource_tsc_page
❯ Booting Windows using QEMU v9.1.1...
BdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,E261DCC3-F035-4749-98A5-CF58E89315B0,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0003 "Windows Boot Manager" from HD(1,GPT,E261DCC3-F035-4749-98A5-CF58E89315B0,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
❯ Shutdown completed!
❯ Starting Windows for Docker v4.06...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Xeon E5 2667 v3 | RAM: 30/32 GB | DISK: 465 GB (v9fs) | KERNEL: 5.15.167.4-microsoft-standard-WSL2...

❯ Warning: unexpected clocksource: hyperv_clocksource_tsc_page
❯ Booting Windows using QEMU v9.1.1...
BdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,E261DCC3-F035-4749-98A5-CF58E89315B0,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0003 "Windows Boot Manager" from HD(1,GPT,E261DCC3-F035-4749-98A5-CF58E89315B0,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
❯ Shutdown completed!
❯ Starting Windows for Docker v4.06...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Xeon E5 2667 v3 | RAM: 30/32 GB | DISK: 477 GB (v9fs) | KERNEL: 5.15.167.4-microsoft-standard-WSL2...

❯ Warning: unexpected clocksource: hyperv_clocksource_tsc_page
❯ Booting Windows using QEMU v9.1.1...
BdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,E261DCC3-F035-4749-98A5-CF58E89315B0,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0003 "Windows Boot Manager" from HD(1,GPT,E261DCC3-F035-4749-98A5-CF58E89315B0,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
❯ Shutdown completed!
❯ Starting Windows for Docker v4.06...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Xeon E5 2667 v3 | RAM: 30/32 GB | DISK: 474 GB (v9fs) | KERNEL: 5.15.167.4-microsoft-standard-WSL2...

❯ Warning: unexpected clocksource: hyperv_clocksource_tsc_page
❯ Booting Windows using QEMU v9.1.1...
BdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,E261DCC3-F035-4749-98A5-CF58E89315B0,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0003 "Windows Boot Manager" from HD(1,GPT,E261DCC3-F035-4749-98A5-CF58E89315B0,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
❯ Received SIGTERM, sending ACPI shutdown signal...
❯ Waiting for Windows to shutdown... (1/110)
❯ Waiting for Windows to shutdown... (2/110)
❯ Waiting for Windows to shutdown... (3/110)
❯ Shutdown completed!
❯ Starting Windows for Docker v4.06...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Xeon E5 2667 v3 | RAM: 30/32 GB | DISK: 475 GB (v9fs) | KERNEL: 5.15.167.4-microsoft-standard-WSL2...

❯ Warning: unexpected clocksource: hyperv_clocksource_tsc_page
❯ Booting Windows using QEMU v9.1.1...
BdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,E261DCC3-F035-4749-98A5-CF58E89315B0,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0003 "Windows Boot Manager" from HD(1,GPT,E261DCC3-F035-4749-98A5-CF58E89315B0,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
❯ Shutdown completed!

**Comment by daurpam** [comment]
Did you activate windows with a license key? 

Last version of windows without a valid activation has this behaviour

**Comment by recluzegeek** [comment]
![image](https://github.com/user-attachments/assets/ff86972d-a592-4ad2-b063-c6511b42ed49)

Yeah its not activated. Any work around for this...Usually used massgrave.dev for activation but its throwing error `Evaluation editions can not be activated beyond the evaluation period.` The [webpage](https://massgrave.dev/evaluation_editions) also mentions

> After the trial period, the system will start showing notifications and may shut down periodically.

Probably needs full version instead of enterprise evaluation in the default `docker-compose.yml`. Also we should highlight this aspect in the `README.md` that enterprise evaluation versions may reboot periodically if not activated to avoid inconvenience.
